package il.ac.hit.todolist.controller;

import il.ac.hit.todolist.model.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

public class TaskController extends Controller {

    public TaskController() { // default constructor
    }

    public TaskController(HttpServletRequest request, HttpServletResponse response) {
        super(request, response);
    }

    private boolean userOwnsTheList(int expectedListID, int providedListID) {
        boolean authorized = true;
        if (expectedListID != providedListID) {
            authorized = false;
            request.setAttribute("error", "You can't access a task from a list you don't own.");
        }
        return authorized;
    }

    public void addTask() throws ToDoListException {
        try {
            User loggedInUser = (User) request.getSession().getAttribute("loggedInUser");
            if (userIsLoggedIn(loggedInUser)) {// the user is logged in
                startTaskInsertion(loggedInUser);
            } else { // [ERROR] unauthorized!
                request.setAttribute("error", "Please login to edit your to do list.");
            }
        } catch (ToDoListException error) {
            System.out.println(error.getMessage());
            error.printStackTrace();
            request.setAttribute("error", error.getMessage());
        } finally {
            redirectToErrorPageIfNecessary();
        }
    }

    private void startTaskInsertion(User loggedInUser) throws ToDoListException {
        int irrelevantTaskID = 00; // task ID is auto generated by hibernate
        String expectedParameters[] = {"description", "deadline"};
        if (requiredParametersProvided(expectedParameters)) {
            Task task = new Task(
                    irrelevantTaskID,
                    loggedInUser.getListID(),
                    request.getParameter("description"),
                    false, // false is default status (not completed yet)
                    request.getParameter("deadline"));
            if (TaskHibernateDAO.getInstance().addItem(task)) {
                try {
                    response.sendRedirect(request.getContextPath() + "/router/task/getTasksList");
                } catch (IOException ex) {
                    throw new ToDoListException(ex.getMessage(), ex);
                }
            } else { // [ERROR]
                request.setAttribute("error", "Can not add task.");
            }
        }
    }

    public void deleteTask() throws ToDoListException {
        try {
            User loggedInUser = (User) request.getSession().getAttribute("loggedInUser");
            if (userIsLoggedIn(loggedInUser)) { // the user is logged in
                startTaskDeletion(loggedInUser.getListID());
            } else  // [ERROR] unauthorized!
                request.setAttribute("error", "Please login to delete your task.");
        } catch (ToDoListException e) {
            request.setAttribute("error", "Delete task error.");
        } finally {
            redirectToErrorPageIfNecessary();
        }
    }

    private void startTaskDeletion(int expectedListID) throws ToDoListException {
        String expectedParameters[] = {"taskID", "listID"};
        if (requiredParametersProvided(expectedParameters) && userOwnsTheList(expectedListID, Integer.parseInt(request.getParameter("listID")))) {
            if (TaskHibernateDAO.getInstance().deleteItem(Integer.parseInt(request.getParameter("taskID")))) {
                try {
                    response.sendRedirect(request.getContextPath() + "/router/task/getTasksList");
                } catch (IOException ex) {
                    throw new ToDoListException(ex.getMessage(), ex);
                }
            } else { // [ERROR]
                request.setAttribute("error", "Wrong task ID provided.");
            }
        }
    }

    public void getTasksList() throws ToDoListException {

        try {
            User loggedInUser = (User) request.getSession().getAttribute("loggedInUser");
            if (userIsLoggedIn(loggedInUser)) {
                List<DBObject> list = TaskHibernateDAO.getInstance().getList(loggedInUser.getListID());
                request.setAttribute("tasks", list);
                request.getServletContext().getRequestDispatcher("/todolist.jsp").forward(request, response);
            } else { // [ERROR] unauthorized!
                request.setAttribute("error", "Please login to get your to do list.");
            }
        } catch (ToDoListException | ServletException | IOException e) {
            request.setAttribute("error", "Get list error.");
        } finally {
            redirectToErrorPageIfNecessary();
        }
    }

    public void updateTaskStatus() throws ToDoListException {
        try {
            User loggedInUser = (User) request.getSession().getAttribute("loggedInUser");
            if (userIsLoggedIn(loggedInUser)) { // the user is logged in
                startTaskStatusUpdate(loggedInUser);
            } else { // [ERROR] unauthorized!
                request.setAttribute("error", "Please login to update a task.");
            }
        } catch (ToDoListException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
            request.setAttribute("error", "Update task error.");
        } finally {
            redirectToErrorPageIfNecessary();
        }
    }

    private void startTaskStatusUpdate(User loggedInUser) throws ToDoListException {
        String expectedParameters[] = {"taskID", "listID", "status"};
        if (requiredParametersProvided(expectedParameters) && userOwnsTheList(loggedInUser.getListID(), Integer.parseInt(request.getParameter("listID")))) {
            int taskIDValue = Integer.parseInt(request.getParameter("taskID"));
            boolean newStatus = Boolean.parseBoolean(request.getParameter("status"));

            if (TaskHibernateDAO.getInstance().updateColumnValue("status", newStatus, "taskID", taskIDValue)) {
                try {
                    response.sendRedirect(request.getContextPath() + "/router/task/getTasksList");
                } catch (IOException ex) {
                    throw new ToDoListException(ex.getMessage(), ex);
                }
            } else { // [ERROR]
                request.setAttribute("error", "Task ID doesn't exist");
            }
        }
    }

}









